services:
  - type: web
    name: drnipa-web
    env: go
    buildCommand: "go build -o main ."
    startCommand: "./main"
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: "8080"